name: sports_app_starter
description: "A sports platform for the UAE market."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Firebase Core Services
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  # Utilities
  intl: ^0.20.2 # ✅ Updated to match Flutter SDK pin
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.0 # ✅ Needed for unit testing

# Note: `flutter_driver` is deprecated and no longer required for most apps.
# Remove it unless you're doing integration tests with it.
# If needed, use integration_test instead.

flutter:
  uses-material-design: true

  # Uncomment when assets are added:
  # assets:
  #   - assets/images/

  # Uncomment when using custom fonts:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf