name: sports_app_starter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.0.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0

flutter:
  uses-material-design: true